// Generated by scripts/inline-bitmap.mjs from phase0/assets/*.bin - do NOT edit.
// Regenerate: npm run bitmap && npm run inline-bitmap

export type AssetId = "ganesh-l" | "ganesh-m" | "ganesh-s" | "om-logo-l" | "om-logo-m" | "om-logo-s";

/** Dots, and the ESC/POS byte cost — the only thing that makes a receipt slow. */
export const ASSET_SIZE: Record<AssetId, { width: number; height: number; bytes: number }> = {
  "ganesh-l": { width: 360, height: 64, bytes: 2888 },
  "ganesh-m": { width: 264, height: 48, bytes: 1592 },
  "ganesh-s": { width: 176, height: 32, bytes: 712 },
  "om-logo-l": { width: 192, height: 184, bytes: 4424 },
  "om-logo-m": { width: 144, height: 144, bytes: 2600 },
  "om-logo-s": { width: 96, height: 96, bytes: 1160 },
};
