// phase0/assets/*.bin -> lib/asset-sizes.ts + lib/asset-bitmaps.ts
//
// Two files on purpose. The preview needs each asset's dimensions to lay the
// page out, and that runs in the browser — it must not drag ~13KB of base64
// raster into the client bundle. Sizes are tiny and safe to ship; the bitmaps
// stay server-only.
//
// Inlined as base64 rather than read from disk so serverless bundling cannot
// lose the files (§8.1: build asset, never a runtime conversion).
import { readFileSync, writeFileSync, readdirSync } from "node:fs";

const DIR = "phase0/assets";
const bins = readdirSync(DIR).filter((f) => f.endsWith(".bin")).sort();
if (!bins.length) throw new Error(`no .bin files in ${DIR} — run: npm run bitmap`);

const HEADER = (from) =>
  `// Generated by scripts/inline-bitmap.mjs from ${from} - do NOT edit.\n` +
  `// Regenerate: npm run bitmap && npm run inline-bitmap\n\n`;

const entries = bins.map((file) => {
  const id = file.replace(/\.bin$/, "");
  const bin = readFileSync(`${DIR}/${file}`);
  // GS v 0 m xL xH yL yH — read the dimensions back out of the command header.
  const width = (bin[4] | (bin[5] << 8)) * 8;
  const height = bin[6] | (bin[7] << 8);
  console.log(`${id.padEnd(12)} ${String(width).padStart(3)}x${String(height).padStart(3)} dots  ${String(bin.length).padStart(5)} bytes`);
  return { id, width, height, bytes: bin.length, b64: bin.toString("base64") };
});

writeFileSync(
  "lib/asset-sizes.ts",
  HEADER("phase0/assets/*.bin") +
    `export type AssetId = ${entries.map((e) => `"${e.id}"`).join(" | ")};\n\n` +
    `/** Dots, and the ESC/POS byte cost — the only thing that makes a receipt slow. */\n` +
    `export const ASSET_SIZE: Record<AssetId, { width: number; height: number; bytes: number }> = {\n` +
    entries
      .map((e) => `  "${e.id}": { width: ${e.width}, height: ${e.height}, bytes: ${e.bytes} },`)
      .join("\n") +
    `\n};\n`,
);

writeFileSync(
  "lib/asset-bitmaps.ts",
  HEADER("phase0/assets/*.bin") +
    `// Server-only: each value is a complete ESC/POS "GS v 0" raster command.\n` +
    `import type { AssetId } from "./asset-sizes";\n\n` +
    `export const ASSET_BITMAP: Record<AssetId, Buffer> = {\n` +
    entries.map((e) => `  "${e.id}": Buffer.from("${e.b64}", "base64"),`).join("\n") +
    `\n};\n`,
);

const total = entries.reduce((n, e) => n + e.bytes, 0);
console.log(`\nlib/asset-sizes.ts + lib/asset-bitmaps.ts written (${entries.length} assets, ${total} bytes)`);
